#region Licence
/* The MIT License (MIT)
Copyright © 2026 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */
#endregion

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Paramore.Brighter.SourceGenerators;

/// <summary>
/// Emits a partial implementation of a user-declared method that registers Brighter handlers
/// and message mappers from the current compilation. The goal is to replace runtime
/// <c>AutoFromAssemblies</c> reflection scanning with compile-time generated registrations.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class BrighterRegistrationsGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Paramore.Brighter.BrighterRegistrationsAttribute";
    private const string ExcludeAttributeName = "Paramore.Brighter.ExcludeFromBrighterRegistrationAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace Paramore.Brighter
        {
            /// <summary>
            /// Marks a <c>partial</c> method that the Brighter source generator will implement
            /// to register handlers and message mappers discovered in the current compilation.
            /// The method must be <c>static partial</c>, return <see cref="Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder"/>,
            /// and take a single <see cref="Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder"/> parameter (extension methods supported).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            internal sealed class BrighterRegistrationsAttribute : global::System.Attribute
            {
            }

            /// <summary>
            /// Excludes a handler / mapper / transform type from automatic Brighter registration.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ExcludeFromBrighterRegistrationAttribute : global::System.Attribute
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("BrighterRegistrationsAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var methodTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol)
            .Where(static m => m is not null)
            .Collect();

        var combined = methodTargets.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var methods = pair.Left;
            var compilation = pair.Right;

            if (methods.IsDefaultOrEmpty)
                return;

            var symbols = MarkerSymbols.Resolve(compilation);
            if (!symbols.IsValid)
            {
                // Brighter not in this compilation's reference graph — nothing to do.
                return;
            }

            var discovered = DiscoverRegistrations(compilation, symbols);

            foreach (var method in methods)
            {
                if (!ValidateMethod(method, symbols, spc, out var diagnostic))
                {
                    spc.ReportDiagnostic(diagnostic!);
                    continue;
                }

                var source = EmitPartial(method, discovered);
                var hint = $"{method.ContainingType.ToDisplayString().Replace('.', '_')}__{method.Name}.g.cs";
                spc.AddSource(hint, SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static bool ValidateMethod(
        IMethodSymbol method,
        MarkerSymbols symbols,
        SourceProductionContext spc,
        out Diagnostic? diagnostic)
    {
        diagnostic = null;

        if (!method.IsPartialDefinition)
        {
            diagnostic = Diagnostic.Create(Diagnostics.MustBePartial, method.Locations.FirstOrDefault(), method.Name);
            return false;
        }

        if (!method.IsStatic)
        {
            diagnostic = Diagnostic.Create(Diagnostics.MustBeStatic, method.Locations.FirstOrDefault(), method.Name);
            return false;
        }

        if (!SymbolEqualityComparer.Default.Equals(method.ReturnType, symbols.BrighterBuilder))
        {
            diagnostic = Diagnostic.Create(Diagnostics.WrongReturnType, method.Locations.FirstOrDefault(), method.Name);
            return false;
        }

        if (method.Parameters.Length != 1 ||
            !SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, symbols.BrighterBuilder))
        {
            diagnostic = Diagnostic.Create(Diagnostics.WrongSignature, method.Locations.FirstOrDefault(), method.Name);
            return false;
        }

        return true;
    }

    private static Registrations DiscoverRegistrations(Compilation compilation, MarkerSymbols symbols)
    {
        var result = new Registrations();
        var excludeAttr = compilation.GetTypeByMetadataName(ExcludeAttributeName);

        foreach (var type in EnumerateNamedTypes(compilation.SourceModule.GlobalNamespace))
        {
            if (!IsRegistrationCandidate(type, excludeAttr))
                continue;

            ClassifyType(type, symbols, result);
        }

        return result;
    }

    private static bool IsRegistrationCandidate(INamedTypeSymbol type, INamedTypeSymbol? excludeAttr)
    {
        if (type.TypeKind != TypeKind.Class)
            return false;
        if (type.IsAbstract || type.IsImplicitClass || type.IsAnonymousType)
            return false;
        if (!IsReachableFromGeneratedCode(type))
            return false;
        if (excludeAttr is not null && HasAttribute(type, excludeAttr))
            return false;
        return true;
    }

    private static bool HasAttribute(INamedTypeSymbol type, INamedTypeSymbol attribute) =>
        type.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attribute));

    private static void ClassifyType(INamedTypeSymbol type, MarkerSymbols symbols, Registrations result)
    {
        var isTransform = false;
        foreach (var iface in type.AllInterfaces)
        {
            if (TryClassifyGenericInterface(type, iface, symbols, result))
                continue;
            if (IsTransformInterface(iface, symbols))
                isTransform = true;
        }

        if (isTransform && !type.IsGenericType)
            result.Transforms.Add(type);
    }

    private static bool TryClassifyGenericInterface(
        INamedTypeSymbol type,
        INamedTypeSymbol iface,
        MarkerSymbols symbols,
        Registrations result)
    {
        if (!iface.IsGenericType || iface.TypeArguments.Length != 1)
            return false;

        var def = iface.OriginalDefinition;
        var requestType = iface.TypeArguments[0];

        if (SymbolEqualityComparer.Default.Equals(def, symbols.HandleRequests))
            result.Handlers.Add((requestType, type));
        else if (SymbolEqualityComparer.Default.Equals(def, symbols.HandleRequestsAsync))
            result.AsyncHandlers.Add((requestType, type));
        else if (SymbolEqualityComparer.Default.Equals(def, symbols.MessageMapper) && !type.IsGenericType)
            result.Mappers.Add((requestType, type));
        else if (SymbolEqualityComparer.Default.Equals(def, symbols.MessageMapperAsync) && !type.IsGenericType)
            result.AsyncMappers.Add((requestType, type));

        return true;
    }

    private static bool IsTransformInterface(INamedTypeSymbol iface, MarkerSymbols symbols) =>
        SymbolEqualityComparer.Default.Equals(iface, symbols.MessageTransform) ||
        SymbolEqualityComparer.Default.Equals(iface, symbols.MessageTransformAsync);

    private static bool IsReachableFromGeneratedCode(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? t = type; t is not null; t = t.ContainingType)
        {
            if (t.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
                return false;
        }
        return true;
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateNamedTypes(INamespaceSymbol ns)
    {
        foreach (var member in ns.GetMembers())
        {
            switch (member)
            {
                case INamespaceSymbol child:
                    foreach (var t in EnumerateNamedTypes(child))
                        yield return t;
                    break;
                case INamedTypeSymbol type:
                    yield return type;
                    foreach (var nested in EnumerateNested(type))
                        yield return nested;
                    break;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateNested(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;
            foreach (var n in EnumerateNested(nested))
                yield return n;
        }
    }

    private static string EmitPartial(IMethodSymbol method, Registrations registrations)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var containingType = method.ContainingType;
        var ns = containingType.ContainingNamespace;
        var hasNamespace = ns is { IsGlobalNamespace: false };

        if (hasNamespace)
        {
            sb.Append("namespace ").Append(ns!.ToDisplayString()).AppendLine();
            sb.AppendLine("{");
        }

        var typeKeyword = containingType.IsStatic ? "static partial class" : "partial class";
        sb.Append("    ").Append(AccessibilityModifier(containingType)).Append(' ').Append(typeKeyword).Append(' ').AppendLine(containingType.Name);
        sb.AppendLine("    {");

        sb.Append("        ").Append(AccessibilityModifier(method)).Append(" static partial ");
        sb.Append(FullyQualified(method.ReturnType)).Append(' ').Append(method.Name).Append('(');
        if (method.IsExtensionMethod)
            sb.Append("this ");
        sb.Append(FullyQualified(method.Parameters[0].Type)).Append(' ').Append(method.Parameters[0].Name);
        sb.AppendLine(")");
        sb.AppendLine("        {");

        EmitHandlers(sb, method.Parameters[0].Name, registrations.Handlers, isAsync: false);
        EmitHandlers(sb, method.Parameters[0].Name, registrations.AsyncHandlers, isAsync: true);
        EmitMappers(sb, method.Parameters[0].Name, registrations.Mappers, registrations.AsyncMappers);
        EmitTransforms(sb, method.Parameters[0].Name, registrations.Transforms);

        sb.Append("            return ").Append(method.Parameters[0].Name).AppendLine(";");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (hasNamespace)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitHandlers(
        StringBuilder sb,
        string paramName,
        List<(ITypeSymbol Request, INamedTypeSymbol Handler)> entries,
        bool isAsync)
    {
        if (entries.Count == 0)
            return;

        var callbackMethod = isAsync ? "AsyncHandlers" : "Handlers";
        sb.Append("            ").Append(paramName).Append('.').Append(callbackMethod).AppendLine("(r =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var registry = (global::Paramore.Brighter.Extensions.DependencyInjection.ServiceCollectionSubscriberRegistry)r;");

        foreach (var (request, handler) in entries)
        {
            if (IsOpenGeneric(handler))
            {
                sb.Append("                registry.EnsureHandlerIsRegistered(typeof(")
                    .Append(UnboundGenericName(handler))
                    .AppendLine("));");
            }
            else
            {
                sb.Append("                registry.Add(typeof(")
                    .Append(FullyQualified(request))
                    .Append("), typeof(")
                    .Append(FullyQualified(handler))
                    .AppendLine("));");
            }
        }

        sb.AppendLine("            });");
    }

    private static void EmitMappers(
        StringBuilder sb,
        string paramName,
        List<(ITypeSymbol Request, INamedTypeSymbol Mapper)> sync,
        List<(ITypeSymbol Request, INamedTypeSymbol Mapper)> async)
    {
        if (sync.Count == 0 && async.Count == 0)
            return;

        sb.Append("            ").Append(paramName).AppendLine(".MapperRegistry(r =>");
        sb.AppendLine("            {");

        foreach (var (request, mapper) in sync)
        {
            sb.Append("                r.Add(typeof(")
                .Append(FullyQualified(request))
                .Append("), typeof(")
                .Append(FullyQualified(mapper))
                .AppendLine("));");
        }

        foreach (var (request, mapper) in async)
        {
            sb.Append("                r.AddAsync(typeof(")
                .Append(FullyQualified(request))
                .Append("), typeof(")
                .Append(FullyQualified(mapper))
                .AppendLine("));");
        }

        sb.AppendLine("            });");
    }

    private static void EmitTransforms(
        StringBuilder sb,
        string paramName,
        List<INamedTypeSymbol> transforms)
    {
        if (transforms.Count == 0)
            return;

        sb.Append("            ").Append(paramName).AppendLine(".Transforms(r =>");
        sb.AppendLine("            {");

        foreach (var transform in transforms)
        {
            sb.Append("                r.Add(typeof(")
                .Append(FullyQualified(transform))
                .AppendLine("));");
        }

        sb.AppendLine("            });");
    }

    private static string FullyQualified(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static bool IsOpenGeneric(INamedTypeSymbol type) =>
        type.IsUnboundGenericType || (type.IsGenericType && type.IsDefinition);

    private static string UnboundGenericName(INamedTypeSymbol type)
    {
        // Emit typeof(Foo<>) syntax for open generics. FullyQualifiedFormat produces Foo<T>;
        // we need Foo<,,>-style instead.
        var name = FullyQualified(type);
        var lt = name.IndexOf('<');
        if (lt < 0)
            return name;
        var arity = type.TypeParameters.Length;
        return name.Substring(0, lt + 1) + new string(',', arity - 1) + ">";
    }

    private static string AccessibilityModifier(ISymbol symbol) => symbol.DeclaredAccessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.ProtectedAndInternal => "private protected",
        _ => "internal"
    };

    private sealed class MarkerSymbols
    {
        public INamedTypeSymbol? BrighterBuilder { get; private set; }
        public INamedTypeSymbol? HandleRequests { get; private set; }
        public INamedTypeSymbol? HandleRequestsAsync { get; private set; }
        public INamedTypeSymbol? MessageMapper { get; private set; }
        public INamedTypeSymbol? MessageMapperAsync { get; private set; }
        public INamedTypeSymbol? MessageTransform { get; private set; }
        public INamedTypeSymbol? MessageTransformAsync { get; private set; }

        public bool IsValid =>
            BrighterBuilder is not null &&
            HandleRequests is not null &&
            HandleRequestsAsync is not null &&
            MessageMapper is not null &&
            MessageMapperAsync is not null &&
            MessageTransform is not null &&
            MessageTransformAsync is not null;

        public static MarkerSymbols Resolve(Compilation c) => new()
        {
            BrighterBuilder = c.GetTypeByMetadataName("Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder"),
            HandleRequests = c.GetTypeByMetadataName("Paramore.Brighter.IHandleRequests`1"),
            HandleRequestsAsync = c.GetTypeByMetadataName("Paramore.Brighter.IHandleRequestsAsync`1"),
            MessageMapper = c.GetTypeByMetadataName("Paramore.Brighter.IAmAMessageMapper`1"),
            MessageMapperAsync = c.GetTypeByMetadataName("Paramore.Brighter.IAmAMessageMapperAsync`1"),
            MessageTransform = c.GetTypeByMetadataName("Paramore.Brighter.IAmAMessageTransform"),
            MessageTransformAsync = c.GetTypeByMetadataName("Paramore.Brighter.IAmAMessageTransformAsync"),
        };
    }

    private sealed class Registrations
    {
        public List<(ITypeSymbol Request, INamedTypeSymbol Handler)> Handlers { get; } = new();
        public List<(ITypeSymbol Request, INamedTypeSymbol Handler)> AsyncHandlers { get; } = new();
        public List<(ITypeSymbol Request, INamedTypeSymbol Mapper)> Mappers { get; } = new();
        public List<(ITypeSymbol Request, INamedTypeSymbol Mapper)> AsyncMappers { get; } = new();
        public List<INamedTypeSymbol> Transforms { get; } = new();
    }

    private static class Diagnostics
    {
        public static readonly DiagnosticDescriptor MustBePartial = new(
            "BRGEN001",
            "Brighter registration method must be partial",
            "Method '{0}' marked with [BrighterRegistrations] must be a partial method",
            "Brighter", DiagnosticSeverity.Error, isEnabledByDefault: true);

        public static readonly DiagnosticDescriptor MustBeStatic = new(
            "BRGEN002",
            "Brighter registration method must be static",
            "Method '{0}' marked with [BrighterRegistrations] must be static",
            "Brighter", DiagnosticSeverity.Error, isEnabledByDefault: true);

        public static readonly DiagnosticDescriptor WrongReturnType = new(
            "BRGEN003",
            "Brighter registration method has wrong return type",
            "Method '{0}' must return IBrighterBuilder",
            "Brighter", DiagnosticSeverity.Error, isEnabledByDefault: true);

        public static readonly DiagnosticDescriptor WrongSignature = new(
            "BRGEN004",
            "Brighter registration method has wrong signature",
            "Method '{0}' must accept a single IBrighterBuilder parameter",
            "Brighter", DiagnosticSeverity.Error, isEnabledByDefault: true);
    }
}
